spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tea_mng?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
#  thymeleaf:
#    prefix: classpath:static/